name: Create release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tagged code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Set packaged manifest version
        run: bun run .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: web

      - name: Build UI
        run: bun run build
        working-directory: web

      - name: Bundle resource
        run: |
          mkdir -p ./temp/ox_inventory/web
          cp ./{server.lua,README.md,LICENSE,fxmanifest.lua,client.lua,init.lua} ./temp/ox_inventory
          cp -r ./{setup,modules,data,locales} ./temp/ox_inventory
          cp -r ./web/build ./temp/ox_inventory/web/build
          cp ./web/LICENSE ./temp/ox_inventory/web/build
          cp -r ./web/images ./temp/ox_inventory/web/images
          cd ./temp
          zip -r ../ox_inventory.zip ox_inventory

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ox_inventory.zip
